# Integrity of the BUILT pkgdown site.
#
# pkgdown-coverage.R checks membership: is every export listed in the reference
# index. This checks the artifact that membership produces -- because a site can
# be listed correctly, build green, and still ship pages that link nowhere.
#
# pkgdown is forgiving by design. A cross-reference to a topic that does not
# exist becomes plain text. An image that is missing becomes a broken <img>. A
# vignette that failed to knit is simply absent. None of those stop the build,
# and the deploy step reports success either way. The failure mode is a site
# that looks complete and is not -- the same shape as every other defect this
# harness exists for.
#
# Run against `docs/` after pkgdown::build_site().

args <- commandArgs(trailingOnly = TRUE)
site <- if (length(args)) args[[1]] else "docs"
if (!dir.exists(site)) {
  stop(sprintf("pkgdown-integrity: no built site at '%s'. Run pkgdown::build_site() first.", site),
       call. = FALSE)
}

fail <- character(0)
note <- function(...) cat(sprintf(...), "\n")
add <- function(...) fail <<- c(fail, sprintf(...))

html <- list.files(site, pattern = "[.]html$", recursive = TRUE, full.names = TRUE)
note("Built site: %s  (%d HTML pages)", site, length(html))
if (!length(html)) add("the site contains no HTML pages at all")

read_all <- function(p) paste(readLines(p, warn = FALSE), collapse = "\n")
pages <- setNames(lapply(html, read_all), html)

# ---------------------------------------------------------------------------
# 1. Every exported function has a rendered reference page
# ---------------------------------------------------------------------------
# A topic can sit in _pkgdown.yml, pass the membership check, and still fail to
# render -- a malformed Rd, a topic aliased away. Membership is a promise; a
# file on disk is the delivery.
exports <- if (file.exists("NAMESPACE")) {
  ns <- readLines("NAMESPACE", warn = FALSE)
  sub('^export\\(([^)]*)\\).*$', '\\1', grep("^export\\(", ns, value = TRUE))
} else character(0)
exports <- gsub('"', '', exports)
ref_dir <- file.path(site, "reference")
missing_pages <- exports[!vapply(exports, function(f)
  file.exists(file.path(ref_dir, paste0(f, ".html"))), logical(1))]
if (length(missing_pages)) {
  add("%d exported function(s) have no rendered reference page: %s",
      length(missing_pages), paste(utils::head(missing_pages, 8), collapse = ", "))
} else {
  note("All %d exported functions have a rendered reference page.", length(exports))
}

# ---------------------------------------------------------------------------
# 2. Internal links resolve to files that exist
# ---------------------------------------------------------------------------
# The quiet one. pkgdown renders an unresolvable \link{} as plain text, so the
# page still looks finished; a stale href renders as a link that 404s only when
# a reader clicks it.
hrefs <- lapply(names(pages), function(p) {
  h <- regmatches(pages[[p]], gregexpr('href="[^"#?]+"', pages[[p]]))[[1]]
  h <- sub('^href="', '', sub('"$', '', h))
  h <- h[!grepl("^(https?:|mailto:|#|//)", h)]
  if (!length(h)) return(NULL)
  data.frame(page = p, href = h, stringsAsFactors = FALSE)
})
hrefs <- do.call(rbind, Filter(Negate(is.null), hrefs))
broken <- character(0)
if (!is.null(hrefs) && nrow(hrefs)) {
  for (i in seq_len(nrow(hrefs))) {
    tgt <- normalizePath(file.path(dirname(hrefs$page[i]), hrefs$href[i]),
                         mustWork = FALSE)
    if (!file.exists(tgt) && !dir.exists(tgt)) {
      broken <- c(broken, sprintf("%s -> %s",
                                  sub(paste0("^", site, "/"), "", hrefs$page[i]),
                                  hrefs$href[i]))
    }
  }
}
if (length(broken)) {
  add("%d internal link(s) point at files that do not exist:\n    %s",
      length(broken), paste(utils::head(broken, 10), collapse = "\n    "))
} else {
  note("All %d internal links resolve.", if (is.null(hrefs)) 0L else nrow(hrefs))
}

# ---------------------------------------------------------------------------
# 3. Referenced images exist
# ---------------------------------------------------------------------------
# README figures are regenerated by data-raw/make_readme_figures.R. If that is
# not re-run after a map change, the site ships the old picture or none.
imgs <- lapply(names(pages), function(p) {
  m <- regmatches(pages[[p]], gregexpr('src="[^"?]+"', pages[[p]]))[[1]]
  m <- sub('^src="', '', sub('"$', '', m))
  m <- m[!grepl("^(https?:|data:|//)", m)]
  if (!length(m)) return(NULL)
  data.frame(page = p, src = m, stringsAsFactors = FALSE)
})
imgs <- do.call(rbind, Filter(Negate(is.null), imgs))
missing_img <- character(0)
if (!is.null(imgs) && nrow(imgs)) {
  for (i in seq_len(nrow(imgs))) {
    tgt <- normalizePath(file.path(dirname(imgs$page[i]), imgs$src[i]), mustWork = FALSE)
    if (!file.exists(tgt)) missing_img <- c(missing_img, imgs$src[i])
  }
}
if (length(missing_img)) {
  add("%d referenced image(s) are absent: %s", length(unique(missing_img)),
      paste(utils::head(unique(missing_img), 6), collapse = ", "))
} else {
  note("All %d referenced images exist.", if (is.null(imgs)) 0L else nrow(imgs))
}

# ---------------------------------------------------------------------------
# 4. Every vignette became an article
# ---------------------------------------------------------------------------
# A vignette that fails to knit is simply missing from the site. Nothing errors.
vig <- list.files("vignettes", pattern = "[.](Rmd|qmd)$", full.names = FALSE)
vig <- vig[!grepl("^_", vig)]
art_dir <- file.path(site, "articles")
missing_art <- character(0)
for (v in vig) {
  stem <- sub("[.](Rmd|qmd)$", "", v)
  if (!file.exists(file.path(art_dir, paste0(stem, ".html")))) {
    missing_art <- c(missing_art, v)
  }
}
if (length(missing_art)) {
  add("%d vignette(s) did not become articles: %s",
      length(missing_art), paste(missing_art, collapse = ", "))
} else {
  note("All %d vignettes rendered as articles.", length(vig))
}

# ---------------------------------------------------------------------------
# 5. Topic count must not silently shrink
# ---------------------------------------------------------------------------
# The regression guard. Losing pages is invisible in a green build; the site
# just gets smaller. A recorded floor turns that into a failure.
floor_file <- ".github/pkgdown-topic-floor.txt"
n_topics <- length(list.files(ref_dir, pattern = "[.]html$"))
if (file.exists(floor_file)) {
  floor <- as.integer(trimws(readLines(floor_file, warn = FALSE)[1]))
  if (!is.na(floor) && n_topics < floor) {
    add("reference topics dropped from %d to %d. If intended, update %s.",
        floor, n_topics, floor_file)
  } else {
    note("Reference topics: %d (floor %d).", n_topics, floor)
  }
} else {
  note("Reference topics: %d (no floor recorded; write %d to %s to enable the guard).",
       n_topics, n_topics, floor_file)
}

# ---------------------------------------------------------------------------
if (length(fail)) {
  cat("\npkgdown site integrity: FAILED\n\n")
  for (f in fail) cat("  * ", f, "\n", sep = "")
  writeLines(sprintf("::error::pkgdown site integrity: %d problem(s)", length(fail)))
  quit(status = 1)
}
cat("\npkgdown site integrity: clean.\n")
